import { 五彩石数据类型 } from '@/@types/五彩石'

const 五彩石_六级: 五彩石数据类型[] = [
  {
    五彩石名称: '彩·星见·激流·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会心', 增益类型: 'atMagicCriticalStrike' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·星见·灭气·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会心', 增益类型: 'atMagicCriticalStrike' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·激流·灭气·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 314, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·激流·月华·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 314, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灭气·激流·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灭气·月华·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·月华·激流·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·月华·灭气·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·无双·激流·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '无双', 增益类型: 'atStrainBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·无双·灭气·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '无双', 增益类型: 'atStrainBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·破招·激流·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破招', 增益类型: 'atSurplusValueBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·破招·灭气·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破招', 增益类型: 'atSurplusValueBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·真元·激流·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '元气', 增益类型: 'atSpunkBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·真元·灭气·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '元气', 增益类型: 'atSpunkBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·星见·激流·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会心', 增益类型: 'atMagicCriticalStrike' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·星见·月华·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会心', 增益类型: 'atMagicCriticalStrike' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·无双·激流·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '无双', 增益类型: 'atStrainBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·无双·月华·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '无双', 增益类型: 'atStrainBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·破招·激流·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破招', 增益类型: 'atSurplusValueBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·破招·月华·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破招', 增益类型: 'atSurplusValueBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·真元·激流·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '元气', 增益类型: 'atSpunkBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·真元·月华·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '元气', 增益类型: 'atSpunkBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·星见·灭气·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会心', 增益类型: 'atMagicCriticalStrike' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·星见·月华·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '会心', 增益类型: 'atMagicCriticalStrike' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·无双·灭气·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '无双', 增益类型: 'atStrainBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·无双·月华·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '无双', 增益类型: 'atStrainBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·破招·灭气·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破招', 增益类型: 'atSurplusValueBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·破招·月华·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 585, 增益名称: '破招', 增益类型: 'atSurplusValueBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·真元·灭气·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '元气', 增益类型: 'atSpunkBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·真元·月华·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '元气', 增益类型: 'atSpunkBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灵根·激流·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '根骨', 增益类型: 'atSpiritBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灵根·灭气·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '根骨', 增益类型: 'atSpiritBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灵根·激流·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '根骨', 增益类型: 'atSpiritBase' },
      { 增益数值: 629, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灵根·月华·激流(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '根骨', 增益类型: 'atSpiritBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 1257, 增益名称: '内攻', 增益类型: 'atMagicAttackPowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灵根·灭气·月华(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '根骨', 增益类型: 'atSpiritBase' },
      { 增益数值: 1170, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
      { 增益数值: 2340, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
  {
    五彩石名称: '彩·灵根·月华·灭气(陆)',
    五彩石等级: 6,
    装备增益: [
      { 增益数值: 131, 增益名称: '根骨', 增益类型: 'atSpiritBase' },
      { 增益数值: 1170, 增益名称: '会效', 增益类型: 'atMagicCriticalDamagePowerBase' },
      { 增益数值: 2340, 增益名称: '破防', 增益类型: 'atMagicOvercome' },
    ],
    DiamondCount1: 14,
    DiamondCount2: 16,
    DiamondCount3: 18,
    DiamondIntensity1: 50,
    DiamondIntensity2: 90,
    DiamondIntensity3: 108,
  },
]

export default 五彩石_六级
